language: cpp

# Need these for a more recent CMake on Linux
sudo: required
dist: trusty

os:
  - osx
  - linux

before_install:
  # macOS commands
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/bin/f2py ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/lib/python2.7 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install opencv3 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "export OpenCV_DIR=/usr/local/opt/opencv3/bin" >> ~/.bash_profile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo 'export PATH="/usr/local/opt/opencv3/bin:$PATH"' >> ~/.bash_profile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ~/.bash_profile ; fi
  # linux commands
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ~ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O opencv.zip https://github.com/Itseez/opencv/archive/3.2.0.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip opencv.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd opencv-3.2.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install ; fi

before_script:
  - cmake .

script:
  - cmake --build .

after_script:
 - cd test
 - ./visionary-test --gtest_color=yes