language: cpp

# Need these for a more recent CMake on Linux
sudo: required
dist: trusty
group: edge

os:
  - osx
  - linux

before_install:
  # osx
  - travis_wait 60 .ci/installOnOSX.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo 'export PATH="/usr/local/opt/opencv3/bin:$PATH"' >> ~/.bash_profile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ~/.bash_profile ; fi
  # linux
  - travis_wait 60 .ci/installOnLinux.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd /home/travis/build/abdullahselek/visionary/ ; fi
  - cmake .

script:
  - cmake --build .

after_script:
 - cd test
 - ./visionary-test --gtest_color=yes